# Generated by Django 3.0.3 on 2020-06-19 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('full_name', models.CharField(max_length=64, primary_key=True, serialize=False, unique=True, verbose_name='Full Name')),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Hourly Rate')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherClock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clock_in', models.DateTimeField()),
                ('clock_out', models.DateTimeField(blank=True)),
                ('full_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.Teacher')),
            ],
        ),
    ]
