# Generated by Django 3.0.3 on 2020-06-19 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacherclock',
            old_name='full_name',
            new_name='teacher',
        ),
    ]
