# Generated by Django 3.0.3 on 2020-07-16 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_auto_20200619_0740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherclock',
            name='clock_out',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
